matrix:
  include:
    - language: python
      python: 
      - 3.6
      before_install:
      - export DJANGO_SETTINGS_MODULE=backend.settings
      - python3 --version
      - pip3 install -r ./backend/requirements.txt
      script:
      - cd ./backend/tests
      - PYTHONPATH=.. pytest -v
    
    - language: node_js
      node_js:
        - 14
      script: 
        - cd ./frontend
        - npm install
        - npm test