matrix:
  include:
    - language: python
      python: 
      - 3.6
      before_install:
      - cd ./backend/
      - python3 --version
      - pip3 install -r requirements.txt
      before_script:
      - python manage.py runserver &
      script:
      - PYTHONPATH=.. pytest -v -p no:warnings
    
    - language: node_js
      node_js:
        - 14
      script: 
        - cd ./frontend
        - npm install
        - npm test