matrix:
  include:
    - language: python
      python: 
      - 3.6
      before_install:
      - python3 --version
      - pip3 install -r ./backend/requirements.txt
      - touch .env
      - echo SECRET_KEY='br^(wet+z_bvav+orj2dnr5f530&o3^5o6!to1k=vo@#kp!nst'">> .env

      script:
      - cd ./backend/tests
      - PYTHONPATH=.. pytest -v
    
    - language: node_js
      node_js:
        - 14
      script: 
        - cd ./frontend
        - npm install
        - npm test