matrix:
  include:
    - language: python
      python: 
      - 3.6
      before_install:
      - python3 --version
      - pip3 install -r ./backend/requirements.txt
      env:
      - DJANGO_VERSION=3.1.7
      - DJANGO_SETTINGS_MODULE='backend.settings'
      script:
      - cd ./backend/tests
      - PYTHONPATH=.. pytest -v
    
    - language: node_js
      node_js:
        - 14
      script: 
        - cd ./frontend
        - npm install
        - npm test