# Generated by Django 3.0.5 on 2021-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=120),
        ),
    ]
