# Generated by Django 3.0.5 on 2021-02-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0005_auto_20210208_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
