# Generated by Django 3.0.5 on 2021-02-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0009_auto_20210225_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
