# Generated by Django 3.0.5 on 2021-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0011_auto_20210226_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diet_plan',
        ),
        migrations.AddField(
            model_name='profile',
            name='cuisin',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='food_type',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
