# Generated by Django 3.0.5 on 2021-03-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0014_auto_20210305_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
